import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Headers } from "@/Components/Headers";
import { Card } from "@/Components/Card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen ml-16">
        <Headers />
        <div className="grid lg:grid-cols-4 gap-4 p-4">
          <Card title={"Total Bets"} amount={20} />
          <Card title={"Total Active Bets"} amount={20} />
          <Card title={"Total Topics"} amount={20} />
          <Card title={"Total Active Topics"} amount={20} />
        </div>
      </main>
    </>
  );
}
